// Audit personas — modelled on real, public Indian creator/brand profiles.
//
// Names, handles, niches and follower magnitudes are taken from public
// rankings (Favikon / Modash / HypeAuditor Aug 2026) and public brand pages so
// the fixtures exercise realistic distributions: a 20M-follower entertainer and
// a 40k-follower nano creator hit very different code paths (price tiers,
// discovery ranking, badge rules), and synthetic "Test User 1..N" data hides
// all of it.
//
// Emails are always @influnet-audit.test so nothing can reach a real inbox and
// these rows are trivially identifiable for purge. Passwords are audit-only.
//
// Deliberate imperfections in this set (do not "fix" them — they are the test):
//   • bewakoof     — left unapproved, to prove the business approval gate
//   • kiranrural   — no Instagram, YouTube only, to prove single-handle signup
//   • nishaanand   — nano tier, to prove discovery doesn't hide small creators
//   • plumgoodness — no GST, to prove GST is genuinely optional

const PW = 'Audit@Influnet2026!';

export const CREATORS = [
  {
    key: 'sourav',
    role: 'influencer',
    name: 'Sourav Joshi',
    username: 'souravjoshi',
    email: 'audit.creator.sourav@influnet-audit.test',
    password: PW,
    phone: '+919812000101',
    gender: 'male',
    city: 'Dehradun',
    state: 'Uttarakhand',
    bio: 'Daily vlogger and artist. Family, travel and everyday stories from Dehradun.',
    niche: ['Entertainment', 'Lifestyle'],
    languages: ['Hindi', 'English'],
    collabTypes: ['YouTube Video', 'Reel', 'Post'],
    priceRange: 'pro',
    instagramHandle: 'souravjoshi2000',
    instagramFollowers: 12_400_000,
    youtubeHandle: '@souravjoshivlogs',
    youtubeSubscribers: 28_600_000,
    tier: 'mega',
  },
  {
    key: 'masoom',
    role: 'influencer',
    name: 'Masoom Minawala',
    username: 'masoomminawala',
    email: 'audit.creator.masoom@influnet-audit.test',
    password: PW,
    phone: '+919812000102',
    gender: 'female',
    city: 'Mumbai',
    state: 'Maharashtra',
    bio: 'Global fashion entrepreneur. Indian luxury on international runways.',
    niche: ['Fashion & Beauty', 'Lifestyle'],
    languages: ['English', 'Hindi', 'Gujarati'],
    collabTypes: ['Reel', 'Story', 'Post', 'Event Appearance'],
    priceRange: 'pro',
    instagramHandle: 'masoomminawala',
    instagramFollowers: 1_340_000,
    youtubeHandle: '@masoomminawala',
    youtubeSubscribers: 68_000,
    tier: 'macro',
  },
  {
    key: 'nagma',
    role: 'influencer',
    name: 'Nagma Mirajkar',
    username: 'nagmamirajkar',
    email: 'audit.creator.nagma@influnet-audit.test',
    password: PW,
    phone: '+919812000103',
    gender: 'female',
    city: 'Mumbai',
    state: 'Maharashtra',
    bio: 'Dance, fashion and lifestyle. Making people smile since Musically.',
    niche: ['Entertainment', 'Fashion & Beauty', 'Music'],
    languages: ['Hindi', 'English', 'Marathi'],
    collabTypes: ['Reel', 'Story', 'Post'],
    priceRange: 'premium',
    instagramHandle: 'nagmaa',
    instagramFollowers: 8_100_000,
    youtubeHandle: '@nagmamirajkar',
    youtubeSubscribers: 1_200_000,
    tier: 'mega',
  },
  {
    key: 'nisha',
    role: 'influencer',
    name: 'Nisha Anand',
    username: 'nishaanand',
    email: 'audit.creator.nisha@influnet-audit.test',
    password: PW,
    phone: '+919812000104',
    gender: 'female',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    bio: 'Home cook. South Indian breakfasts, one reel at a time.',
    niche: ['Food & Cooking'],
    languages: ['Tamil', 'English'],
    collabTypes: ['Reel', 'Post'],
    priceRange: 'entry',
    instagramHandle: 'nishacooksdaily',
    instagramFollowers: 41_200,
    tier: 'nano',
  },
  {
    key: 'kiran',
    role: 'influencer',
    name: 'Kiran Rathore',
    username: 'kiranrural',
    email: 'audit.creator.kiran@influnet-audit.test',
    password: PW,
    phone: '+919812000105',
    gender: 'male',
    city: 'Jodhpur',
    state: 'Rajasthan',
    // No Instagram on purpose — the signup schema requires at least ONE handle,
    // not specifically Instagram. Everything downstream (discovery, media kit,
    // ownership verification) must cope with an Instagram-less creator.
    bio: 'Rural life, farming and desert travel from Rajasthan.',
    niche: ['Travel', 'Education'],
    languages: ['Hindi', 'English'],
    collabTypes: ['YouTube Video'],
    priceRange: 'standard',
    youtubeHandle: '@kiranruraldiaries',
    youtubeSubscribers: 486_000,
    tier: 'mid',
  },
  {
    key: 'arjunfit',
    role: 'influencer',
    name: 'Arjun Menon',
    username: 'arjunfitindia',
    email: 'audit.creator.arjun@influnet-audit.test',
    password: PW,
    phone: '+919812000106',
    gender: 'male',
    city: 'Bengaluru',
    state: 'Karnataka',
    bio: 'Strength coach. Evidence-based fitness for Indian bodies and Indian food.',
    niche: ['Fitness & Health', 'Education'],
    languages: ['English', 'Malayalam', 'Kannada'],
    collabTypes: ['Reel', 'YouTube Video', 'Post'],
    priceRange: 'premium',
    instagramHandle: 'arjunfitindia',
    instagramFollowers: 612_000,
    youtubeHandle: '@arjunfitindia',
    youtubeSubscribers: 240_000,
    tier: 'macro',
  },
];

export const BUSINESSES = [
  {
    key: 'mamaearth',
    role: 'business_owner',
    name: 'Ritika Sharma',
    companyName: 'Mamaearth',
    businessUsername: 'mamaearth',
    email: 'audit.biz.mamaearth@influnet-audit.test',
    password: PW,
    phone: '+919822000201',
    industry: 'Beauty & Personal Care',
    businessType: 'D2C Brand',
    website: 'https://mamaearth.in',
    gstNumber: '06AABCU9603R1ZM',
    registeredAddress: 'Plot 8, Udyog Vihar Phase IV, Gurugram 122015',
    marketingBudget: '₹5L – ₹10L',
    city: 'Gurugram',
    state: 'Haryana',
    collabPreferences: ['Reel', 'Story', 'Post'],
    approve: true,
  },
  {
    key: 'boat',
    role: 'business_owner',
    name: 'Karan Mehta',
    companyName: 'boAt Lifestyle',
    businessUsername: 'boatlifestyle',
    email: 'audit.biz.boat@influnet-audit.test',
    password: PW,
    phone: '+919822000202',
    industry: 'Technology',
    businessType: 'D2C Brand',
    website: 'https://boat-lifestyle.com',
    gstNumber: '27AABCB1234C1Z5',
    registeredAddress: 'One Boat HQ, Lower Parel, Mumbai 400013',
    marketingBudget: '₹10L+',
    city: 'Mumbai',
    state: 'Maharashtra',
    collabPreferences: ['Reel', 'YouTube Video', 'Event Appearance'],
    approve: true,
  },
  {
    key: 'sugar',
    role: 'business_owner',
    name: 'Ananya Iyer',
    companyName: 'SUGAR Cosmetics',
    businessUsername: 'sugarcosmetics',
    email: 'audit.biz.sugar@influnet-audit.test',
    password: PW,
    phone: '+919822000203',
    industry: 'Beauty & Personal Care',
    businessType: 'D2C Brand',
    website: 'https://in.sugarcosmetics.com',
    gstNumber: '27AAFCV1234H1Z9',
    registeredAddress: 'Kanakia Wall Street, Andheri East, Mumbai 400093',
    marketingBudget: '₹1L – ₹5L',
    city: 'Mumbai',
    state: 'Maharashtra',
    collabPreferences: ['Reel', 'Story'],
    approve: true,
  },
  {
    key: 'wakefit',
    role: 'business_owner',
    name: 'Deepak Nair',
    companyName: 'Wakefit Innovations',
    businessUsername: 'wakefit',
    email: 'audit.biz.wakefit@influnet-audit.test',
    password: PW,
    phone: '+919822000204',
    industry: 'Home & Lifestyle',
    businessType: 'E-commerce',
    website: 'https://wakefit.co',
    gstNumber: '29AAGCW1234K1ZT',
    registeredAddress: 'Koramangala 3rd Block, Bengaluru 560034',
    marketingBudget: '₹50K – ₹1L',
    city: 'Bengaluru',
    state: 'Karnataka',
    collabPreferences: ['Reel', 'Post'],
    approve: true,
  },
  {
    key: 'plum',
    role: 'business_owner',
    name: 'Sneha Kulkarni',
    companyName: 'Plum Goodness',
    businessUsername: 'plumgoodness',
    email: 'audit.biz.plum@influnet-audit.test',
    password: PW,
    phone: '+919822000205',
    industry: 'Beauty & Personal Care',
    businessType: 'Startup',
    website: 'https://plumgoodness.com',
    // No GST on purpose — it is an optional field and signup must not demand it.
    registeredAddress: 'Powai, Mumbai 400076',
    marketingBudget: 'Under ₹25K/month',
    city: 'Mumbai',
    state: 'Maharashtra',
    collabPreferences: ['Post'],
    approve: true,
  },
  {
    key: 'bewakoof',
    role: 'business_owner',
    name: 'Rohit Agarwal',
    companyName: 'Bewakoof Brands',
    businessUsername: 'bewakoof',
    email: 'audit.biz.bewakoof@influnet-audit.test',
    password: PW,
    phone: '+919822000206',
    industry: 'Fashion & Apparel',
    businessType: 'D2C Brand',
    website: 'https://bewakoof.com',
    gstNumber: '27AAECB5678M1ZP',
    registeredAddress: 'Kandivali East, Mumbai 400101',
    marketingBudget: '₹1L – ₹5L',
    city: 'Mumbai',
    state: 'Maharashtra',
    collabPreferences: ['Reel', 'Post'],
    // Left in pending_review on purpose — proves the approval gate actually
    // blocks collab requests rather than only hiding a button.
    approve: false,
  },
];

export const ALL_PERSONAS = [...CREATORS, ...BUSINESSES];
export const AUDIT_EMAIL_DOMAIN = '@influnet-audit.test';
export const AUDIT_PASSWORD = PW;

export function personaByKey(key) {
  const p = ALL_PERSONAS.find((x) => x.key === key);
  if (!p) throw new Error(`No persona "${key}"`);
  return p;
}
