/**
 * Renders every template to .email-preview/ and builds an index page.
 *
 * The admin console at /dashboard/admin/emails is the real tool — this exists
 * so the whole set can be eyeballed at once without an admin login or a running
 * server, which is what you want when changing the shared shell in layout.ts.
 *
 * Run:  npm run email:preview
 * Then: open apps/web/.email-preview/index.html
 */
import { writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { TEMPLATES, type TemplateDef } from '../src/lib/email/templates';
import { theme } from '../src/lib/email/theme';

const outDir = resolve(dirname(fileURLToPath(import.meta.url)), '../.email-preview');
mkdirSync(outDir, { recursive: true });

// Object.values() over a heterogeneous registry gives TS an intersection of
// every template's data type; each one only ever renders its own sample, so
// widen to the base shape rather than satisfying an impossible intersection.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const all = Object.values(TEMPLATES) as TemplateDef<any>[];

const entries = all.map((tpl) => {
  const sample = tpl.sample as Record<string, unknown>;
  const html = tpl.render(sample, {
    unsubscribeUrl: tpl.tier === 'account' ? undefined : 'https://influnet.io/api/email/unsubscribe?t=preview',
  });
  const file = `${tpl.id}.html`;
  writeFileSync(resolve(outDir, file), html, 'utf8');
  return { ...tpl, file, subject: tpl.subject(sample) };
});

const rows = entries
  .map(
    (e) => `
  <a class="card" href="${e.file}" target="preview">
    <span class="tier tier-${e.tier}">${e.tier}</span>
    <strong>${e.label}</strong>
    <span class="subject">${e.subject}</span>
  </a>`,
  )
  .join('');

writeFileSync(
  resolve(outDir, 'index.html'),
  `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Influnet email templates</title>
<style>
  body { margin:0; font-family:${theme.font}; background:${theme.page}; display:grid; grid-template-columns:340px 1fr; height:100vh; }
  aside { overflow-y:auto; padding:20px; border-right:1px solid ${theme.border}; background:#fff; }
  h1 { font-size:15px; margin:0 0 4px; color:${theme.ink}; }
  p.lead { font-size:12px; color:${theme.muted}; margin:0 0 18px; }
  .card { display:block; padding:12px 14px; border:1px solid ${theme.border}; border-radius:12px; margin-bottom:8px; text-decoration:none; }
  .card:hover { border-color:${theme.brand}; }
  .card strong { display:block; font-size:14px; color:${theme.ink}; margin:6px 0 3px; }
  .subject { font-size:12px; color:${theme.muted}; }
  .tier { font-size:10px; font-weight:700; text-transform:uppercase; letter-spacing:.08em; padding:2px 7px; border-radius:20px; }
  .tier-account { background:${theme.brandSoft}; color:${theme.brand}; }
  .tier-activity { background:#eef4ff; color:#2c5fd0; }
  .tier-marketing { background:${theme.panel}; color:${theme.muted}; }
  iframe { border:0; width:100%; height:100%; background:${theme.page}; }
</style></head>
<body>
  <aside>
    <h1>Influnet email templates</h1>
    <p class="lead">${entries.length} templates · generated by npm run email:preview</p>
    ${rows}
  </aside>
  <iframe name="preview" src="${entries[0]?.file ?? 'about:blank'}"></iframe>
</body></html>`,
  'utf8',
);

console.log(`✓ ${entries.length} templates → apps/web/.email-preview/index.html`);
