const { createClient } = require('@supabase/supabase-js');

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://hrpaqufvjcihnjrjnpej.supabase.co';
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'sb_publishable_ebIIalxnJ-fYMr6I2N-EpQ_6TV5kaBy';

const sb = createClient(supabaseUrl, supabaseKey);

console.log(`[DEBUG] Connecting to Supabase URL: ${supabaseUrl}`);
console.log(`[DEBUG] Supabase Key prefix: ${supabaseKey ? supabaseKey.substring(0, 15) : 'undefined'}...`);

// Random suffixes to avoid user collisions
const suffix = Math.floor(Math.random() * 1000000);
const brandEmail = `testbrand_${suffix}@influnet.com`;
const creatorEmail = `testcreator_${suffix}@influnet.com`;
const password = 'TestPassword123!';

async function delay(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function signUpUser(email, name, role) {
  console.log(`- Signing up ${role} (${email})...`);
  const { data, error } = await sb.auth.signUp({
    email,
    password,
    options: {
      data: {
        name,
        role
      }
    }
  });
  if (error) throw error;
  
  let session = data.session;
  if (!session) {
    console.log(`- User exists or needs sign in, logging in...`);
    const { data: logData, error: logError } = await sb.auth.signInWithPassword({ email, password });
    if (logError) throw logError;
    session = logData.session;
  }

  // Register profile role in profiles table via public.register_profile RPC
  console.log(`- Registering profile in database...`);
  const payload = {
    role,
    email,
    name,
    location: 'Mumbai, India',
    phone: '+919999999999'
  };
  if (role === 'business_owner') {
    payload.companyName = `Test Company ${suffix}`;
    payload.industry = 'Tech';
  } else {
    payload.username = `creator_${suffix}`;
    payload.bio = `Hi, I am a creator named Vimal ${suffix}`;
    payload.niche = ['Fashion', 'Lifestyle'];
    payload.instagramHandle = `vimal_${suffix}`;
  }

  const regRes = await fetch('http://localhost:3000/api/auth/register', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${session.access_token}`
    },
    body: JSON.stringify(payload)
  });

  if (!regRes.ok) {
    const regErr = await regRes.json().catch(() => ({}));
    throw new Error(`Profile registration failed: ${regErr.error || regRes.statusText}`);
  }

  return session;
}

async function runTests() {
  console.log("=================================================");
  console.log("   INFLUNET END-TO-END MATCHMAKING TEST SUITE    ");
  console.log("=================================================");

  let brandSession, creatorSession;
  let createdCollabId;
  let createdProjectId;

  try {
    // ----------------------------------------------------
    // TEST 1: Register Accounts
    // ----------------------------------------------------
    console.log("\n[TEST 1] Registering test accounts...");
    brandSession = await signUpUser(brandEmail, `Brand Corp ${suffix}`, 'business_owner');
    console.log(`✓ Brand registered. User ID: ${brandSession.user.id}`);
    
    creatorSession = await signUpUser(creatorEmail, `Creator Vimal ${suffix}`, 'influencer');
    console.log(`✓ Creator registered. User ID: ${creatorSession.user.id}`);

    // Wait a brief moment to ensure DB profile records are fully generated by triggers
    await delay(1500);

    // ----------------------------------------------------
    // TEST 2: Unidirectional Pitch Enforcement
    // ----------------------------------------------------
    console.log("\n[TEST 2] Testing unidirectional pitching restrictions...");
    console.log("- Trying to send request from Creator to Brand (Should Fail)...");
    const failRes = await fetch('http://localhost:3000/api/collabs', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${creatorSession.access_token}`
      },
      body: JSON.stringify({
        to_user_id: brandSession.user.id,
        project_title: 'Unlawful Proposal',
        project_description: 'Creator proposing to brand',
        budget: 5000
      })
    });

    const failBody = await failRes.json();
    console.log(`- Response Status: ${failRes.status}`);
    console.log(`- Response Body:`, failBody);

    if (failRes.status === 403) {
      console.log("✓ Correctly blocked Creator from pitching brand (403 Forbidden).");
    } else {
      throw new Error(`Expected 403 status, got ${failRes.status}`);
    }

    // ----------------------------------------------------
    // TEST 3: Correct Collab Request (Brand to Creator)
    // ----------------------------------------------------
    console.log("\n[TEST 3] Sending valid collab request (Brand to Creator)...");
    const collabRes = await fetch('http://localhost:3000/api/collabs', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${brandSession.access_token}`
      },
      body: JSON.stringify({
        to_user_id: creatorSession.user.id,
        project_title: `Festive Campaign ${suffix}`,
        project_description: 'Shoot 3 high-quality Instagram reels showcasing our brand packaging.',
        budget: 25000
      })
    });

    const collabBody = await collabRes.json();
    console.log(`- Response Status: ${collabRes.status}`);
    console.log(`- Response Body:`, collabBody);

    if (collabRes.status === 200 && collabBody.collab && collabBody.collab.id) {
      createdCollabId = collabBody.collab.id;
      console.log(`✓ Collab Request sent successfully. ID: ${createdCollabId}`);
    } else {
      throw new Error(`Collab creation failed: ${collabBody.error || 'Unknown error'}`);
    }

    // ----------------------------------------------------
    // TEST 4: Unique Open Request Constraint
    // ----------------------------------------------------
    console.log("\n[TEST 4] Testing duplicate open request constraint...");
    console.log("- Trying to send second pending request to same creator...");
    const dupRes = await fetch('http://localhost:3000/api/collabs', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${brandSession.access_token}`
      },
      body: JSON.stringify({
        to_user_id: creatorSession.user.id,
        project_title: `Another Pitch`,
        project_description: 'Spam pitch',
        budget: 1000
      })
    });

    const dupBody = await dupRes.json();
    console.log(`- Response Status: ${dupRes.status}`);
    console.log(`- Response Body:`, dupBody);

    if (dupRes.status === 500 && (dupBody.error?.includes('unique') || dupBody.error?.includes('collab_requests_one_pending_per_pair'))) {
      console.log("✓ Duplicate pending request correctly blocked by database constraint.");
    } else {
      console.log(`⚠ Warning: Expected DB unique constraint failure, got ${dupRes.status}. Check database schemas.`);
    }

    // ----------------------------------------------------
    // TEST 5: Acceptance & Auto-Creation Handshake
    // ----------------------------------------------------
    console.log("\n[TEST 5] Accepting request (Creator action)...");
    const acceptRes = await fetch('http://localhost:3000/api/collabs', {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${creatorSession.access_token}`
      },
      body: JSON.stringify({
        id: createdCollabId,
        status: 'accepted'
      })
    });

    const acceptBody = await acceptRes.json();
    console.log(`- Response Status: ${acceptRes.status}`);
    console.log(`- Response Body:`, acceptBody);

    if (acceptRes.status !== 200) {
      throw new Error(`Accept request failed: ${acceptBody.error}`);
    }
    console.log("✓ Collab request state transitioned to accepted.");

    // Wait for DB async triggers or server processes
    await delay(1000);

    // ----------------------------------------------------
    // TEST 6: Project & Conversation Validation
    // ----------------------------------------------------
    console.log("\n[TEST 6] Validating campaign project creation & stages...");
    console.log("- Fetching projects as Brand (triggers RLS-compatible self-healing reconciliation)...");
    const brandProjectsRes = await fetch('http://localhost:3000/api/projects', {
      headers: {
        'Authorization': `Bearer ${brandSession.access_token}`
      }
    });

    const projectsRes = await fetch('http://localhost:3000/api/projects', {
      headers: {
        'Authorization': `Bearer ${creatorSession.access_token}`
      }
    });

    const projectsBody = await projectsRes.json();
    console.log(`- Creator Projects Response Status: ${projectsRes.status}`);
    console.log(`- Projects Found: ${projectsBody.projects?.length || 0}`);

    const matchingProj = (projectsBody.projects || []).find(p => p.owner_user_id === brandSession.user.id && p.counterparty_user_id === creatorSession.user.id);
    
    if (matchingProj) {
      createdProjectId = matchingProj.id;
      console.log(`✓ Project found in database! ID: ${createdProjectId}`);
      console.log(`✓ Current stage initialized as: ${matchingProj.current_stage}`);
    } else {
      throw new Error("Reconciliation failed: Accepted collab request did not generate a campaign project workspace!");
    }

    // ----------------------------------------------------
    // TEST 7: Project Stage Advancement
    // ----------------------------------------------------
    console.log("\n[TEST 7] Testing stage advancement timeline...");
    const advanceRes = await fetch('http://localhost:3000/api/projects', {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${brandSession.access_token}`
      },
      body: JSON.stringify({
        id: createdProjectId,
        current_stage: 'project_discussion',
        status: 'active'
      })
    });

    const advanceBody = await advanceRes.json();
    console.log(`- Response Status: ${advanceRes.status}`);
    console.log(`- Updated Project Stage: ${advanceBody.project?.current_stage}`);

    if (advanceRes.status === 200 && advanceBody.project?.current_stage === 'project_discussion') {
      console.log("✓ Project successfully advanced to project_discussion!");
    } else {
      throw new Error(`Failed to advance stage: ${advanceBody.error}`);
    }

    console.log("\n=================================================");
    console.log("       ALL INTEGRATION TESTS PASSED SUCCESSFULLY!       ");
    console.log("=================================================");

  } catch (err) {
    console.error("\n❌ TEST SUITE FAILED:", err.message);
    process.exit(1);
  }
}

runTests();
