/**
 * Receipt / proforma PDF template using @react-pdf/renderer.
 *
 * Renders from a frozen snapshot — never re-reads live data. The snapshot
 * is captured at issue time and stored in project_documents.snapshot.
 */
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: 'Helvetica' },
  header: { marginBottom: 20, borderBottomWidth: 1, borderBottomColor: '#e2e8f0', paddingBottom: 10 },
  title: { fontSize: 18, fontWeight: 'bold', marginBottom: 4 },
  subtitle: { fontSize: 10, color: '#64748b' },
  row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4 },
  label: { color: '#64748b', width: '40%' },
  value: { fontWeight: 'bold', width: '60%', textAlign: 'right' },
  section: { marginTop: 16 },
  sectionTitle: { fontSize: 12, fontWeight: 'bold', marginBottom: 8, textTransform: 'uppercase', color: '#64748b' },
  total: { marginTop: 12, paddingTop: 8, borderTopWidth: 1, borderTopColor: '#e2e8f0', fontSize: 14, fontWeight: 'bold' },
  watermark: { position: 'absolute', top: '40%', left: '20%', fontSize: 40, color: '#fca5a5', transform: 'rotate(-45deg)', opacity: 0.3 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 8, color: '#94a3b8', textAlign: 'center' },
});

export interface ReceiptSnapshot {
  kind: 'proforma' | 'receipt';
  number: string;
  project: { title: string; description?: string };
  parties: { issuer: string; recipient: string };
  deliverables?: string;
  amountPaise: number;
  currency: string;
  payments: Array<{ stage: string; amountPaise: number; status: string; paidAt?: string }>;
  issuedAt: string;
}

export function ReceiptDocument({ snapshot }: { snapshot: ReceiptSnapshot }) {
  const totalRupees = (snapshot.amountPaise / 100).toLocaleString('en-IN');
  const isProforma = snapshot.kind === 'proforma';
  const hasPaid = snapshot.payments.some((p) => p.status === 'paid');

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {isProforma && !hasPaid && <Text style={styles.watermark}>NOT A RECEIPT</Text>}

        <View style={styles.header}>
          <Text style={styles.title}>{isProforma ? 'Proforma Invoice' : 'Receipt'}</Text>
          <Text style={styles.subtitle}>#{snapshot.number}</Text>
        </View>

        <View style={styles.row}>
          <Text style={styles.label}>From</Text>
          <Text style={styles.value}>{snapshot.parties.issuer}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>To</Text>
          <Text style={styles.value}>{snapshot.parties.recipient}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Project</Text>
          <Text style={styles.value}>{snapshot.project.title}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Date</Text>
          <Text style={styles.value}>{new Date(snapshot.issuedAt).toLocaleDateString('en-IN')}</Text>
        </View>

        {snapshot.deliverables && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Deliverables</Text>
            <Text>{snapshot.deliverables}</Text>
          </View>
        )}

        {snapshot.payments.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Payments</Text>
            {snapshot.payments.map((p, i) => (
              <View key={i} style={styles.row}>
                <Text style={styles.label}>{p.stage.replace(/_/g, ' ')}</Text>
                <Text style={styles.value}>
                  ₹{(p.amountPaise / 100).toLocaleString('en-IN')} — {p.status}
                </Text>
              </View>
            ))}
          </View>
        )}

        <View style={styles.row}>
          <Text style={[styles.label, { fontSize: 12 }]}>Total</Text>
          <Text style={styles.total}>₹{totalRupees}</Text>
        </View>

        <Text style={styles.footer}>
          Generated by Influnet · {snapshot.number} · {new Date(snapshot.issuedAt).toISOString()}
        </Text>
      </Page>
    </Document>
  );
}
