-- Migration 070: Admin hardening + privilege-escalation fix.
--
-- ══ THE HOLE THIS CLOSES ═════════════════════════════════════════════════
-- `profiles_update_own` (001) allows a user to UPDATE their own row, with no
-- WITH CHECK clause and no column restriction. Supabase's stock bootstrap
-- grants UPDATE on public tables to `authenticated`, and migration 048 revoked
-- only SELECT on profiles — never UPDATE. So any logged-in user could run
--
--     PATCH /rest/v1/profiles?id=eq.<their own id>   {"role":"admin"}
--
-- with nothing but their own access token, and become a platform admin.
-- Verified against the real schema: the UPDATE succeeds and the role sticks.
--
-- Migration 049 blocked admin self-registration through register_profile(),
-- but that only covers signup — it never protected the UPDATE path.
--
-- ══ THE FIX (three independent layers) ═══════════════════════════════════
--  1. Column grants — `authenticated` may only UPDATE the columns a user
--     legitimately edits. `role` is not among them. Column privileges are
--     enforced before RLS, so this alone stops the attack.
--  2. A trigger — any change to role / verification_status / verified_badge
--     must come from a privileged backend connection, never a user session.
--     This survives someone re-granting the column by mistake.
--  3. WITH CHECK on the RLS policy — a row a user updates must still be
--     their own row afterwards.
--
-- Layers 1 and 2 are deliberately redundant. Privilege escalation is the one
-- failure that compromises every other control, so it gets belt and braces.

-- ---------------------------------------------------------------------------
-- 1. Column-level UPDATE grants
-- ---------------------------------------------------------------------------
REVOKE UPDATE ON public.profiles FROM authenticated;
REVOKE UPDATE ON public.profiles FROM anon;

-- Exactly the fields a person may edit about themselves. Note that `email` is
-- absent: it belongs to auth.users and changing it here would desync identity.
GRANT UPDATE (name, location, phone, updated_at)
  ON public.profiles TO authenticated;

-- ---------------------------------------------------------------------------
-- 2. Trigger guard on the privileged columns
-- ---------------------------------------------------------------------------
-- Distinguishes "a user session" from "the backend". Under Supabase, a user
-- request runs as the `authenticated` (or `anon`) role; the service-role key
-- and migrations run as `service_role` / `postgres`. SECURITY DEFINER
-- functions owned by the table owner also pass, which is what lets
-- admin_decide_verification() keep working.
CREATE OR REPLACE FUNCTION public.is_privileged_connection()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
AS $$
  SELECT current_user NOT IN ('authenticated', 'anon');
$$;

CREATE OR REPLACE FUNCTION public.guard_profile_privileges()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF public.is_privileged_connection() THEN
    RETURN NEW;
  END IF;

  IF NEW.role IS DISTINCT FROM OLD.role THEN
    RAISE EXCEPTION 'role cannot be changed from a user session'
      USING ERRCODE = '42501';
  END IF;

  IF NEW.verification_status IS DISTINCT FROM OLD.verification_status
     OR NEW.verified_badge IS DISTINCT FROM OLD.verified_badge
     OR NEW.verified_at IS DISTINCT FROM OLD.verified_at THEN
    RAISE EXCEPTION 'verification state cannot be changed from a user session'
      USING ERRCODE = '42501';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS profiles_guard_privileges ON public.profiles;
CREATE TRIGGER profiles_guard_privileges
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.guard_profile_privileges();

-- ---------------------------------------------------------------------------
-- 3. RLS policy gains a WITH CHECK
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- ---------------------------------------------------------------------------
-- 4. Admin audit log
-- ---------------------------------------------------------------------------
-- The admin account is shared with the client, so "which admin did what, when"
-- has to be answerable after the fact. Append-only by construction: no UPDATE
-- or DELETE policy exists, and none should be added.
CREATE TABLE IF NOT EXISTS public.admin_audit_log (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id    UUID REFERENCES public.profiles (id) ON DELETE SET NULL,
  actor_email TEXT,
  action      TEXT NOT NULL,
  target_id   UUID,
  target_type TEXT,
  metadata    JSONB NOT NULL DEFAULT '{}'::jsonb,
  ip_address  TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS admin_audit_log_created_idx
  ON public.admin_audit_log (created_at DESC);
CREATE INDEX IF NOT EXISTS admin_audit_log_actor_idx
  ON public.admin_audit_log (actor_id, created_at DESC);

ALTER TABLE public.admin_audit_log ENABLE ROW LEVEL SECURITY;

-- Admins may read the trail. Nobody writes it from a user session — inserts go
-- through the service-role backend, which bypasses RLS.
DROP POLICY IF EXISTS admin_audit_log_select ON public.admin_audit_log;
CREATE POLICY admin_audit_log_select ON public.admin_audit_log
  FOR SELECT TO authenticated
  USING (public.is_admin());

REVOKE INSERT, UPDATE, DELETE ON public.admin_audit_log FROM authenticated, anon;

-- ---------------------------------------------------------------------------
-- 5. provision_admin() — the ONLY supported way to mint an admin
-- ---------------------------------------------------------------------------
-- Callable only from a privileged connection (the service-role key), so it can
-- never be reached from a browser session even if the grant is fumbled. The
-- auth.users row must already exist; scripts/create-admin.mjs creates it via
-- the Auth Admin API and then calls this.
CREATE OR REPLACE FUNCTION public.provision_admin(
  p_user_id UUID,
  p_email   TEXT,
  p_name    TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_existing public.user_role;
BEGIN
  IF NOT public.is_privileged_connection() THEN
    RAISE EXCEPTION 'provision_admin requires a privileged connection'
      USING ERRCODE = '42501';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE id = p_user_id) THEN
    RAISE EXCEPTION 'auth user % does not exist', p_user_id;
  END IF;

  SELECT role INTO v_existing FROM public.profiles WHERE id = p_user_id;

  INSERT INTO public.profiles (id, role, email, name, verification_status)
  VALUES (p_user_id, 'admin', p_email, coalesce(p_name, 'Platform Admin'), 'verified')
  ON CONFLICT (id) DO UPDATE
    SET role = 'admin',
        name = coalesce(EXCLUDED.name, public.profiles.name),
        verification_status = 'verified',
        updated_at = now();

  INSERT INTO public.admin_audit_log (actor_id, actor_email, action, target_id, target_type, metadata)
  VALUES (p_user_id, p_email, 'admin_provisioned', p_user_id, 'profile',
          jsonb_build_object('previous_role', v_existing));

  RETURN jsonb_build_object('user_id', p_user_id, 'email', p_email, 'role', 'admin',
                            'previous_role', v_existing);
END;
$$;

REVOKE EXECUTE ON FUNCTION public.provision_admin(UUID, TEXT, TEXT) FROM PUBLIC, anon, authenticated;

-- ---------------------------------------------------------------------------
-- 6. revoke_admin() — demotion is as important as promotion
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.revoke_admin(
  p_user_id  UUID,
  p_new_role public.user_role DEFAULT 'influencer'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.is_privileged_connection() THEN
    RAISE EXCEPTION 'revoke_admin requires a privileged connection'
      USING ERRCODE = '42501';
  END IF;

  IF p_new_role = 'admin' THEN
    RAISE EXCEPTION 'use provision_admin to grant admin';
  END IF;

  UPDATE public.profiles SET role = p_new_role, updated_at = now()
  WHERE id = p_user_id AND role = 'admin';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'user % is not an admin', p_user_id;
  END IF;

  INSERT INTO public.admin_audit_log (actor_id, action, target_id, target_type, metadata)
  VALUES (p_user_id, 'admin_revoked', p_user_id, 'profile',
          jsonb_build_object('new_role', p_new_role));

  RETURN jsonb_build_object('user_id', p_user_id, 'role', p_new_role);
END;
$$;

REVOKE EXECUTE ON FUNCTION public.revoke_admin(UUID, public.user_role) FROM PUBLIC, anon, authenticated;
