-- Migration 109: rate-limit visibility for the admin console.
--
-- The limiter itself (apps/web/src/lib/rate-limit.ts) has run since the
-- 2026-07-14 hardening pass, but it has never recorded anything — a 429
-- disappears into a log line with no bucket or caller attached. There is
-- nothing to derive this from (unlike get_user_activity/get_platform_activity,
-- which read rows that already existed for other reasons), so this is a new
-- aggregate table: one row per (bucket, caller, hour), incremented in place,
-- not one row per request. Written from apps/web/src/lib/rate-limit-log.ts,
-- best-effort and never blocking the request it describes — same shape as
-- admin_audit_log (070).

CREATE TABLE IF NOT EXISTS public.rate_limit_stats (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bucket         TEXT NOT NULL,
  -- A user id (UUID text) when the route keys by an authenticated caller,
  -- otherwise the client IP resolved by clientKey(). Deliberately untyped —
  -- the admin UI decides how to render it (UUID-shaped -> join profiles).
  identity       TEXT NOT NULL,
  window_start   TIMESTAMPTZ NOT NULL,
  request_count  INT NOT NULL DEFAULT 0,
  limited_count  INT NOT NULL DEFAULT 0,
  limit_value    INT,
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (bucket, identity, window_start)
);

CREATE INDEX IF NOT EXISTS rate_limit_stats_window_idx
  ON public.rate_limit_stats (window_start DESC);
CREATE INDEX IF NOT EXISTS rate_limit_stats_bucket_idx
  ON public.rate_limit_stats (bucket, window_start DESC);

ALTER TABLE public.rate_limit_stats ENABLE ROW LEVEL SECURITY;

-- Admins may read it directly; nobody writes it from a user session — inserts
-- go through the service-role backend, which bypasses RLS.
DROP POLICY IF EXISTS rate_limit_stats_select ON public.rate_limit_stats;
CREATE POLICY rate_limit_stats_select ON public.rate_limit_stats
  FOR SELECT TO authenticated
  USING (public.is_admin());

REVOKE INSERT, UPDATE, DELETE ON public.rate_limit_stats FROM authenticated, anon;

-- Called from apps/web/src/lib/rate-limit-log.ts via the service-role client
-- only — same "service_role already has schema-wide execute, just lock
-- everyone else out" shape as provision_admin/revoke_admin (070). Not
-- SECURITY DEFINER: the caller already IS the privileged role, no elevation
-- needed, and this keeps the function honest about who's allowed to call it.
CREATE OR REPLACE FUNCTION public.record_rate_limit_hit(
  p_bucket       TEXT,
  p_identity     TEXT,
  p_window_start TIMESTAMPTZ,
  p_limited      BOOLEAN,
  p_limit        INT
)
RETURNS VOID
LANGUAGE sql
SET search_path = public
AS $$
  INSERT INTO public.rate_limit_stats (bucket, identity, window_start, request_count, limited_count, limit_value)
  VALUES (p_bucket, p_identity, p_window_start, 1, CASE WHEN p_limited THEN 1 ELSE 0 END, p_limit)
  ON CONFLICT (bucket, identity, window_start) DO UPDATE
  SET request_count = public.rate_limit_stats.request_count + 1,
      limited_count = public.rate_limit_stats.limited_count + (CASE WHEN p_limited THEN 1 ELSE 0 END),
      limit_value   = excluded.limit_value,
      updated_at    = now();
$$;

REVOKE EXECUTE ON FUNCTION public.record_rate_limit_hit(TEXT, TEXT, TIMESTAMPTZ, BOOLEAN, INT) FROM PUBLIC, anon, authenticated;
