-- Migration 134: expose creating_since on the public profile RPC
--
-- S2 has been settable on both platforms since the previous session, but
-- never displayed anywhere — the value never left the profiles table.
-- get_public_influencer() is the single RPC both /c/[username] and the
-- shared /api/creators/[username] JSON view (which mobile also calls) read
-- from, so this one change reaches both platforms at once.
--
-- Additive only: one new DECLARE, one column added to two existing SELECTs,
-- one new key added to each of the two RETURN branches (primary username
-- match, legacy custom-slug match). Nothing else in this function changed —
-- generated by patching the live function definition byte-for-byte rather
-- than retyping the whole 180-line function from a read, given how many
-- existing profile fields depend on this RPC staying correct.

CREATE OR REPLACE FUNCTION public.get_public_influencer(p_slug text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_user_id UUID;
  v_name TEXT;
  v_location TEXT;
  v_verified BOOLEAN;
  v_ownership_verified BOOLEAN;
  v_creating_since SMALLINT;
  v_ip public.influencer_profiles%ROWTYPE;
  needle TEXT;
  slug_custom TEXT;
  rec RECORD;
BEGIN
  needle := lower(trim(coalesce(p_slug, '')));
  IF needle = '' THEN
    RETURN NULL;
  END IF;

  -- Primary: dedicated username
  SELECT p.id, p.name, p.location, p.verified_badge, p.creating_since
  INTO v_user_id, v_name, v_location, v_verified, v_creating_since
  FROM public.profiles p
  INNER JOIN public.influencer_profiles ip ON ip.user_id = p.id
  WHERE p.role = 'influencer'
    AND ip.username IS NOT NULL
    AND ip.username <> ''
    AND lower(ip.username) = needle
  LIMIT 1;

  IF v_user_id IS NOT NULL THEN
    SELECT * INTO v_ip FROM public.influencer_profiles WHERE user_id = v_user_id;
    SELECT EXISTS (
      SELECT 1 FROM public.social_account_claims c
      WHERE c.user_id = v_user_id
        AND c.platform = 'instagram'
        AND c.status = 'verified'
        AND c.handle = lower(trim(coalesce(v_ip.instagram_handle, '')))
    ) INTO v_ownership_verified;

    RETURN jsonb_build_object(
      'userId', v_user_id,
      'name', v_name,
      'location', v_location,
      'city', v_ip.city,
      'state', v_ip.state,
      'username', v_ip.username,
      'profileSlug', v_ip.username,
      'headline', v_ip.headline,
      'bio', v_ip.bio,
      'niche', coalesce(v_ip.niche, '[]'::jsonb),
      'avatarUrl', v_ip.avatar_url,
      'coverImageUrl', v_ip.cover_image_url,
      'availabilityStatus', v_ip.availability_status,
      'audienceDemographics', coalesce(v_ip.audience_demographics, '{}'::jsonb),
      'pastCollaborations', coalesce(v_ip.past_collaborations, '[]'::jsonb),
      'isVerified', coalesce(v_verified, false),
      'ownershipVerified', coalesce(v_ownership_verified, false),
      'creatingSince', v_creating_since,
      'instagramHandle', v_ip.instagram_handle,
      'youtubeHandle', v_ip.youtube_handle,
      'twitterHandle', v_ip.twitter_handle,
      'facebookHandle', v_ip.facebook_handle,
      'linkedinHandle', v_ip.linkedin_handle,
      'tiktokHandle', v_ip.tiktok_handle,
      'instagramFollowers', coalesce(v_ip.instagram_followers, 0),
      'youtubeSubscribers', coalesce(v_ip.youtube_subscribers, 0),
      'tiktokFollowers', coalesce(v_ip.tiktok_followers, 0),
      'facebookFollowers', coalesce(v_ip.facebook_followers, 0),
      'engagementRate', v_ip.engagement_rate,
      'mediaKitUrl', v_ip.media_kit_url,
      'portfolio', coalesce(v_ip.portfolio, '[]'::jsonb),
      'pricingMin', v_ip.pricing_min,
      'pricingMax', v_ip.pricing_max,
      'collabTypes', coalesce(v_ip.collab_types, '[]'::jsonb),
      'priceRange', v_ip.price_range,
      'languages', coalesce(v_ip.languages, '[]'::jsonb)
    );
  END IF;

  -- Legacy: custom profile_slug (hyphen slugs)
  FOR rec IN
    SELECT p.id, p.name, p.location, p.verified_badge, p.creating_since
    FROM public.profiles p
    WHERE p.role = 'influencer'
  LOOP
    SELECT * INTO v_ip FROM public.influencer_profiles WHERE user_id = rec.id;
    slug_custom := lower(
      trim(
        both '-'
        from regexp_replace(lower(trim(coalesce(v_ip.profile_slug, ''))), '[^a-z0-9]+', '-', 'g')
      )
    );
    IF slug_custom <> '' AND slug_custom = lower(regexp_replace(needle, '[^a-z0-9]+', '-', 'g')) THEN
      SELECT EXISTS (
        SELECT 1 FROM public.social_account_claims c
        WHERE c.user_id = rec.id
          AND c.platform = 'instagram'
          AND c.status = 'verified'
          AND c.handle = lower(trim(coalesce(v_ip.instagram_handle, '')))
      ) INTO v_ownership_verified;

      RETURN jsonb_build_object(
        'userId', rec.id,
        'name', rec.name,
        'location', rec.location,
        'city', v_ip.city,
        'state', v_ip.state,
        'username', v_ip.username,
        'profileSlug', coalesce(v_ip.username, slug_custom),
        'headline', v_ip.headline,
        'bio', v_ip.bio,
        'niche', coalesce(v_ip.niche, '[]'::jsonb),
        'avatarUrl', v_ip.avatar_url,
        'coverImageUrl', v_ip.cover_image_url,
        'availabilityStatus', v_ip.availability_status,
        'audienceDemographics', coalesce(v_ip.audience_demographics, '{}'::jsonb),
        'pastCollaborations', coalesce(v_ip.past_collaborations, '[]'::jsonb),
        'isVerified', coalesce(rec.verified_badge, false),
        'ownershipVerified', coalesce(v_ownership_verified, false),
        'creatingSince', rec.creating_since,
        'instagramHandle', v_ip.instagram_handle,
        'youtubeHandle', v_ip.youtube_handle,
        'twitterHandle', v_ip.twitter_handle,
        'facebookHandle', v_ip.facebook_handle,
        'linkedinHandle', v_ip.linkedin_handle,
        'tiktokHandle', v_ip.tiktok_handle,
        'instagramFollowers', coalesce(v_ip.instagram_followers, 0),
        'youtubeSubscribers', coalesce(v_ip.youtube_subscribers, 0),
        'tiktokFollowers', coalesce(v_ip.tiktok_followers, 0),
        'facebookFollowers', coalesce(v_ip.facebook_followers, 0),
        'engagementRate', v_ip.engagement_rate,
        'mediaKitUrl', v_ip.media_kit_url,
        'portfolio', coalesce(v_ip.portfolio, '[]'::jsonb),
        'pricingMin', v_ip.pricing_min,
        'pricingMax', v_ip.pricing_max,
        'collabTypes', coalesce(v_ip.collab_types, '[]'::jsonb),
        'priceRange', v_ip.price_range,
        'languages', coalesce(v_ip.languages, '[]'::jsonb)
      );
    END IF;
  END LOOP;

  RETURN NULL;
END;
$function$
